// tslint:disable: max-classes-per-file

export class ActivityNotExistsError extends Error {}
export class TimeCoveredNotExistsError extends Error {}
export class ChallengeNotExistsError extends Error {}
export class EmailAlreadyUsedError extends Error {}
export class PhoneNumberAlreadyUsedError extends Error {}
export class UserNotFoundError extends Error {}
export class UserIsNotInvitedError extends Error {}
export class InvitaionCodeError extends Error {}
export class UserAlreadyRegisteredError extends Error {}
export class UserOtpSessionExpiredError extends Error {}
export class NotAuthorizedException extends Error {}
export class UserNotRegisteredError extends Error {}
export class PatientExistsError extends Error {}
export class EmailPhoneAlreadyInUse extends Error {}
export class IncorrectEmailOrPassword extends Error {}
export class InvalidPasswordException extends Error {}
export class InvalidSession extends Error {}
export class MissingRelationError extends Error {}
export class MissingEntityError extends Error {}
export class NotAuthorisedError extends Error {}
export class UserAlreadyExist extends Error {}
export class OTPInvalidError extends Error {}
export class UpdatePlanError extends Error {}
export class DietPlanExistsError extends Error {}
export class DuplicatePlanError extends Error {}
export class DietPlanDetailsError extends Error {}
export class GetDietPlanError extends Error {}
export class DeleteDietPlanFailed extends Error {}
export class DietPlanListFailed extends Error {}
export class MasterPlanError extends Error {}
export class FailedToCopy extends Error {}
export class UserAlreadyHasthePlan extends Error {}
export class NoPlanDetails extends Error {}
export class SystolicPressureMissingError extends Error {}
export class DiastolicPressureMissingError extends Error {}
export class TempratureUnitMissingError extends Error {}
export class FailedToCreateVitals extends Error {}
export class HighBloodPressure extends Error {}
export class LowBloodPressure extends Error {}
export class InputValidationError extends Error {}
export class PatientAssociatedWithDoctorError extends Error {}
export class InputValidationErrorForWeight extends Error {}
export class ClinicNotFound extends Error {}
export class ClinicAdminNotFound extends Error {}
export class NoClinicFoundForTheUid extends Error {}
export class CoachNotFound extends Error {}
export class PatientAlreadyLinked extends Error {}
export class NoDataFound extends Error {}
export class CodeExpiredError extends Error {}
export class CodeMismatchError extends Error {}
export class UserStatusConfirmedError extends Error {}
export class InvalidEmailPhoneException extends Error {}
export class InvalidCategoryError extends Error {}
export class CardTitleExistsError extends Error {}
